2022-04-30 07:59:15,903 - aplikasi - ERROR - Exception on /master/post_akun_bank [POST]
Traceback (most recent call last):
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/limaoper/bagi_pulsa/aplikasi/master/routes.py", line 280, in post_akun_bank
    kode_bank = hsl_data_bank[0]['kode_bank']
IndexError: list index out of range
2022-04-30 07:59:17,862 - aplikasi - ERROR - Exception on /master/post_akun_bank [POST]
Traceback (most recent call last):
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/limaoper/bagi_pulsa/aplikasi/master/routes.py", line 280, in post_akun_bank
    kode_bank = hsl_data_bank[0]['kode_bank']
IndexError: list index out of range
2022-04-30 07:59:18,348 - aplikasi - ERROR - Exception on /master/post_akun_bank [POST]
Traceback (most recent call last):
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/limaoper/bagi_pulsa/aplikasi/master/routes.py", line 280, in post_akun_bank
    kode_bank = hsl_data_bank[0]['kode_bank']
IndexError: list index out of range
2022-04-30 07:59:18,552 - aplikasi - ERROR - Exception on /master/post_akun_bank [POST]
Traceback (most recent call last):
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/limaoper/bagi_pulsa/aplikasi/master/routes.py", line 280, in post_akun_bank
    kode_bank = hsl_data_bank[0]['kode_bank']
IndexError: list index out of range
2022-04-30 07:59:18,626 - aplikasi - ERROR - Exception on /master/post_akun_bank [POST]
Traceback (most recent call last):
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/limaoper/bagi_pulsa/aplikasi/master/routes.py", line 280, in post_akun_bank
    kode_bank = hsl_data_bank[0]['kode_bank']
IndexError: list index out of range
2022-04-30 07:59:18,768 - aplikasi - ERROR - Exception on /master/post_akun_bank [POST]
Traceback (most recent call last):
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/limaoper/bagi_pulsa/aplikasi/master/routes.py", line 280, in post_akun_bank
    kode_bank = hsl_data_bank[0]['kode_bank']
IndexError: list index out of range
2022-04-30 07:59:18,947 - aplikasi - ERROR - Exception on /master/post_akun_bank [POST]
Traceback (most recent call last):
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/limaoper/bagi_pulsa/aplikasi/master/routes.py", line 280, in post_akun_bank
    kode_bank = hsl_data_bank[0]['kode_bank']
IndexError: list index out of range
2022-04-30 07:59:19,097 - aplikasi - ERROR - Exception on /master/post_akun_bank [POST]
Traceback (most recent call last):
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/limaoper/bagi_pulsa/aplikasi/master/routes.py", line 280, in post_akun_bank
    kode_bank = hsl_data_bank[0]['kode_bank']
IndexError: list index out of range
2022-04-30 07:59:19,280 - aplikasi - ERROR - Exception on /master/post_akun_bank [POST]
Traceback (most recent call last):
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/limaoper/bagi_pulsa/aplikasi/master/routes.py", line 280, in post_akun_bank
    kode_bank = hsl_data_bank[0]['kode_bank']
IndexError: list index out of range
2022-04-30 07:59:19,510 - aplikasi - ERROR - Exception on /master/post_akun_bank [POST]
Traceback (most recent call last):
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/limaoper/bagi_pulsa/aplikasi/master/routes.py", line 280, in post_akun_bank
    kode_bank = hsl_data_bank[0]['kode_bank']
IndexError: list index out of range
2022-04-30 07:59:19,612 - aplikasi - ERROR - Exception on /master/post_akun_bank [POST]
Traceback (most recent call last):
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/limaoper/bagi_pulsa/aplikasi/master/routes.py", line 280, in post_akun_bank
    kode_bank = hsl_data_bank[0]['kode_bank']
IndexError: list index out of range
2022-04-30 07:59:19,778 - aplikasi - ERROR - Exception on /master/post_akun_bank [POST]
Traceback (most recent call last):
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/limaoper/bagi_pulsa/aplikasi/master/routes.py", line 280, in post_akun_bank
    kode_bank = hsl_data_bank[0]['kode_bank']
IndexError: list index out of range
2022-04-30 07:59:19,941 - aplikasi - ERROR - Exception on /master/post_akun_bank [POST]
Traceback (most recent call last):
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/limaoper/bagi_pulsa/aplikasi/master/routes.py", line 280, in post_akun_bank
    kode_bank = hsl_data_bank[0]['kode_bank']
IndexError: list index out of range
2022-04-30 07:59:20,091 - aplikasi - ERROR - Exception on /master/post_akun_bank [POST]
Traceback (most recent call last):
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/limaoper/bagi_pulsa/aplikasi/master/routes.py", line 280, in post_akun_bank
    kode_bank = hsl_data_bank[0]['kode_bank']
IndexError: list index out of range
2022-04-30 07:59:20,343 - aplikasi - ERROR - Exception on /master/post_akun_bank [POST]
Traceback (most recent call last):
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/limaoper/bagi_pulsa/aplikasi/master/routes.py", line 280, in post_akun_bank
    kode_bank = hsl_data_bank[0]['kode_bank']
IndexError: list index out of range
2022-04-30 07:59:20,572 - aplikasi - ERROR - Exception on /master/post_akun_bank [POST]
Traceback (most recent call last):
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/limaoper/bagi_pulsa/aplikasi/master/routes.py", line 280, in post_akun_bank
    kode_bank = hsl_data_bank[0]['kode_bank']
IndexError: list index out of range
