2022-04-19 20:46:58,104 - aplikasi - ERROR - Exception on /master/post_akun_bank [POST]
Traceback (most recent call last):
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/limaoper/bagi_pulsa/aplikasi/master/routes.py", line 280, in post_akun_bank
    kode_bank = hsl_data_bank[0]['kode_bank']
IndexError: list index out of range
2022-04-19 20:47:02,336 - aplikasi - ERROR - Exception on /master/post_akun_bank [POST]
Traceback (most recent call last):
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/limaoper/bagi_pulsa/aplikasi/master/routes.py", line 280, in post_akun_bank
    kode_bank = hsl_data_bank[0]['kode_bank']
IndexError: list index out of range
2022-04-19 20:47:02,967 - aplikasi - ERROR - Exception on /master/post_akun_bank [POST]
Traceback (most recent call last):
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/limaoper/bagi_pulsa/aplikasi/master/routes.py", line 280, in post_akun_bank
    kode_bank = hsl_data_bank[0]['kode_bank']
IndexError: list index out of range
2022-04-19 20:47:03,362 - aplikasi - ERROR - Exception on /master/post_akun_bank [POST]
Traceback (most recent call last):
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/limaoper/bagi_pulsa/aplikasi/master/routes.py", line 280, in post_akun_bank
    kode_bank = hsl_data_bank[0]['kode_bank']
IndexError: list index out of range
2022-04-19 20:47:03,522 - aplikasi - ERROR - Exception on /master/post_akun_bank [POST]
Traceback (most recent call last):
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/limaoper/bagi_pulsa/aplikasi/master/routes.py", line 280, in post_akun_bank
    kode_bank = hsl_data_bank[0]['kode_bank']
IndexError: list index out of range
2022-04-19 20:47:03,687 - aplikasi - ERROR - Exception on /master/post_akun_bank [POST]
Traceback (most recent call last):
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/limaoper/bagi_pulsa/aplikasi/master/routes.py", line 280, in post_akun_bank
    kode_bank = hsl_data_bank[0]['kode_bank']
IndexError: list index out of range
2022-04-19 20:47:03,764 - aplikasi - ERROR - Exception on /master/post_akun_bank [POST]
Traceback (most recent call last):
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/limaoper/bagi_pulsa/aplikasi/master/routes.py", line 280, in post_akun_bank
    kode_bank = hsl_data_bank[0]['kode_bank']
IndexError: list index out of range
2022-04-19 20:47:04,010 - aplikasi - ERROR - Exception on /master/post_akun_bank [POST]
Traceback (most recent call last):
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/limaoper/bagi_pulsa/aplikasi/master/routes.py", line 280, in post_akun_bank
    kode_bank = hsl_data_bank[0]['kode_bank']
IndexError: list index out of range
2022-04-19 20:47:04,172 - aplikasi - ERROR - Exception on /master/post_akun_bank [POST]
Traceback (most recent call last):
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/limaoper/bagi_pulsa/aplikasi/master/routes.py", line 280, in post_akun_bank
    kode_bank = hsl_data_bank[0]['kode_bank']
IndexError: list index out of range
2022-04-19 20:47:04,321 - aplikasi - ERROR - Exception on /master/post_akun_bank [POST]
Traceback (most recent call last):
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/limaoper/bagi_pulsa/aplikasi/master/routes.py", line 280, in post_akun_bank
    kode_bank = hsl_data_bank[0]['kode_bank']
IndexError: list index out of range
2022-04-19 20:47:04,570 - aplikasi - ERROR - Exception on /master/post_akun_bank [POST]
Traceback (most recent call last):
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/limaoper/bagi_pulsa/aplikasi/master/routes.py", line 280, in post_akun_bank
    kode_bank = hsl_data_bank[0]['kode_bank']
IndexError: list index out of range
2022-04-19 20:47:04,726 - aplikasi - ERROR - Exception on /master/post_akun_bank [POST]
Traceback (most recent call last):
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/limaoper/bagi_pulsa/aplikasi/master/routes.py", line 280, in post_akun_bank
    kode_bank = hsl_data_bank[0]['kode_bank']
IndexError: list index out of range
2022-04-19 20:47:04,821 - aplikasi - ERROR - Exception on /master/post_akun_bank [POST]
Traceback (most recent call last):
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/limaoper/bagi_pulsa/aplikasi/master/routes.py", line 280, in post_akun_bank
    kode_bank = hsl_data_bank[0]['kode_bank']
IndexError: list index out of range
2022-04-19 20:47:04,968 - aplikasi - ERROR - Exception on /master/post_akun_bank [POST]
Traceback (most recent call last):
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/limaoper/bagi_pulsa/aplikasi/master/routes.py", line 280, in post_akun_bank
    kode_bank = hsl_data_bank[0]['kode_bank']
IndexError: list index out of range
2022-04-19 20:47:05,208 - aplikasi - ERROR - Exception on /master/post_akun_bank [POST]
Traceback (most recent call last):
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/limaoper/bagi_pulsa/aplikasi/master/routes.py", line 280, in post_akun_bank
    kode_bank = hsl_data_bank[0]['kode_bank']
IndexError: list index out of range
2022-04-19 20:47:05,428 - aplikasi - ERROR - Exception on /master/post_akun_bank [POST]
Traceback (most recent call last):
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/limaoper/bagi_pulsa/aplikasi/master/routes.py", line 280, in post_akun_bank
    kode_bank = hsl_data_bank[0]['kode_bank']
IndexError: list index out of range
2022-04-19 20:47:05,605 - aplikasi - ERROR - Exception on /master/post_akun_bank [POST]
Traceback (most recent call last):
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/limaoper/bagi_pulsa/aplikasi/master/routes.py", line 280, in post_akun_bank
    kode_bank = hsl_data_bank[0]['kode_bank']
IndexError: list index out of range
2022-04-19 20:47:05,857 - aplikasi - ERROR - Exception on /master/post_akun_bank [POST]
Traceback (most recent call last):
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/limaoper/bagi_pulsa/aplikasi/master/routes.py", line 280, in post_akun_bank
    kode_bank = hsl_data_bank[0]['kode_bank']
IndexError: list index out of range
