2022-08-11 16:07:01,833 - aplikasi - ERROR - Exception on /master/post_akun_bank [POST]
Traceback (most recent call last):
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/limaoper/bagi_pulsa/aplikasi/master/routes.py", line 300, in post_akun_bank
    kode_bank = hsl_data_bank[0]['kode_bank']
IndexError: list index out of range
2022-08-11 16:07:04,360 - aplikasi - ERROR - Exception on /master/post_akun_bank [POST]
Traceback (most recent call last):
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/limaoper/bagi_pulsa/aplikasi/master/routes.py", line 300, in post_akun_bank
    kode_bank = hsl_data_bank[0]['kode_bank']
IndexError: list index out of range
2022-08-11 19:47:42,668 - aplikasi - ERROR - Exception on /master/post_akun_bank [POST]
Traceback (most recent call last):
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/limaoper/bagi_pulsa/aplikasi/master/routes.py", line 300, in post_akun_bank
    kode_bank = hsl_data_bank[0]['kode_bank']
IndexError: list index out of range
2022-08-11 19:47:43,511 - aplikasi - ERROR - Exception on /master/post_akun_bank [POST]
Traceback (most recent call last):
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/limaoper/bagi_pulsa/aplikasi/master/routes.py", line 300, in post_akun_bank
    kode_bank = hsl_data_bank[0]['kode_bank']
IndexError: list index out of range
2022-08-11 19:47:44,504 - aplikasi - ERROR - Exception on /master/post_akun_bank [POST]
Traceback (most recent call last):
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/limaoper/bagi_pulsa/aplikasi/master/routes.py", line 300, in post_akun_bank
    kode_bank = hsl_data_bank[0]['kode_bank']
IndexError: list index out of range
2022-08-11 19:47:44,852 - aplikasi - ERROR - Exception on /master/post_akun_bank [POST]
Traceback (most recent call last):
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/limaoper/bagi_pulsa/aplikasi/master/routes.py", line 300, in post_akun_bank
    kode_bank = hsl_data_bank[0]['kode_bank']
IndexError: list index out of range
2022-08-11 19:47:45,027 - aplikasi - ERROR - Exception on /master/post_akun_bank [POST]
Traceback (most recent call last):
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/limaoper/bagi_pulsa/aplikasi/master/routes.py", line 300, in post_akun_bank
    kode_bank = hsl_data_bank[0]['kode_bank']
IndexError: list index out of range
2022-08-11 19:47:45,485 - aplikasi - ERROR - Exception on /master/post_akun_bank [POST]
Traceback (most recent call last):
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/limaoper/bagi_pulsa/aplikasi/master/routes.py", line 300, in post_akun_bank
    kode_bank = hsl_data_bank[0]['kode_bank']
IndexError: list index out of range
2022-08-11 19:47:45,512 - aplikasi - ERROR - Exception on /master/post_akun_bank [POST]
Traceback (most recent call last):
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/limaoper/bagi_pulsa/aplikasi/master/routes.py", line 300, in post_akun_bank
    kode_bank = hsl_data_bank[0]['kode_bank']
IndexError: list index out of range
2022-08-11 19:47:45,637 - aplikasi - ERROR - Exception on /master/post_akun_bank [POST]
Traceback (most recent call last):
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/limaoper/bagi_pulsa/aplikasi/master/routes.py", line 300, in post_akun_bank
    kode_bank = hsl_data_bank[0]['kode_bank']
IndexError: list index out of range
2022-08-11 19:47:45,804 - aplikasi - ERROR - Exception on /master/post_akun_bank [POST]
Traceback (most recent call last):
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/limaoper/bagi_pulsa/aplikasi/master/routes.py", line 300, in post_akun_bank
    kode_bank = hsl_data_bank[0]['kode_bank']
IndexError: list index out of range
2022-08-11 19:47:46,086 - aplikasi - ERROR - Exception on /master/post_akun_bank [POST]
Traceback (most recent call last):
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/limaoper/bagi_pulsa/aplikasi/master/routes.py", line 300, in post_akun_bank
    kode_bank = hsl_data_bank[0]['kode_bank']
IndexError: list index out of range
2022-08-11 19:47:46,205 - aplikasi - ERROR - Exception on /master/post_akun_bank [POST]
Traceback (most recent call last):
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/limaoper/bagi_pulsa/aplikasi/master/routes.py", line 300, in post_akun_bank
    kode_bank = hsl_data_bank[0]['kode_bank']
IndexError: list index out of range
2022-08-11 19:47:46,680 - aplikasi - ERROR - Exception on /master/post_akun_bank [POST]
Traceback (most recent call last):
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/limaoper/bagi_pulsa/aplikasi/master/routes.py", line 300, in post_akun_bank
    kode_bank = hsl_data_bank[0]['kode_bank']
IndexError: list index out of range
2022-08-11 19:47:47,942 - aplikasi - ERROR - Exception on /master/post_akun_bank [POST]
Traceback (most recent call last):
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/limaoper/bagi_pulsa/aplikasi/master/routes.py", line 300, in post_akun_bank
    kode_bank = hsl_data_bank[0]['kode_bank']
IndexError: list index out of range
2022-08-11 19:47:48,260 - aplikasi - ERROR - Exception on /master/post_akun_bank [POST]
Traceback (most recent call last):
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/limaoper/bagi_pulsa/aplikasi/master/routes.py", line 300, in post_akun_bank
    kode_bank = hsl_data_bank[0]['kode_bank']
IndexError: list index out of range
2022-08-11 19:47:48,614 - aplikasi - ERROR - Exception on /master/post_akun_bank [POST]
Traceback (most recent call last):
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/limaoper/bagi_pulsa/aplikasi/master/routes.py", line 300, in post_akun_bank
    kode_bank = hsl_data_bank[0]['kode_bank']
IndexError: list index out of range
2022-08-11 19:47:49,130 - aplikasi - ERROR - Exception on /master/post_akun_bank [POST]
Traceback (most recent call last):
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/limaoper/bagi_pulsa/aplikasi/master/routes.py", line 300, in post_akun_bank
    kode_bank = hsl_data_bank[0]['kode_bank']
IndexError: list index out of range
2022-08-11 19:47:49,504 - aplikasi - ERROR - Exception on /master/post_akun_bank [POST]
Traceback (most recent call last):
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/limaoper/bagi_pulsa/aplikasi/master/routes.py", line 300, in post_akun_bank
    kode_bank = hsl_data_bank[0]['kode_bank']
IndexError: list index out of range
2022-08-11 19:47:49,967 - aplikasi - ERROR - Exception on /master/post_akun_bank [POST]
Traceback (most recent call last):
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/limaoper/bagi_pulsa/aplikasi/master/routes.py", line 300, in post_akun_bank
    kode_bank = hsl_data_bank[0]['kode_bank']
IndexError: list index out of range
2022-08-11 19:47:50,073 - aplikasi - ERROR - Exception on /master/post_akun_bank [POST]
Traceback (most recent call last):
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/limaoper/bagi_pulsa/aplikasi/master/routes.py", line 300, in post_akun_bank
    kode_bank = hsl_data_bank[0]['kode_bank']
IndexError: list index out of range
2022-08-11 19:47:50,417 - aplikasi - ERROR - Exception on /master/post_akun_bank [POST]
Traceback (most recent call last):
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/limaoper/bagi_pulsa/aplikasi/master/routes.py", line 300, in post_akun_bank
    kode_bank = hsl_data_bank[0]['kode_bank']
IndexError: list index out of range
2022-08-11 19:47:50,593 - aplikasi - ERROR - Exception on /master/post_akun_bank [POST]
Traceback (most recent call last):
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/limaoper/bagi_pulsa/aplikasi/master/routes.py", line 300, in post_akun_bank
    kode_bank = hsl_data_bank[0]['kode_bank']
IndexError: list index out of range
2022-08-11 19:47:51,325 - aplikasi - ERROR - Exception on /master/post_akun_bank [POST]
Traceback (most recent call last):
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/limaoper/bagi_pulsa/aplikasi/master/routes.py", line 300, in post_akun_bank
    kode_bank = hsl_data_bank[0]['kode_bank']
IndexError: list index out of range
2022-08-11 19:47:51,448 - aplikasi - ERROR - Exception on /master/post_akun_bank [POST]
Traceback (most recent call last):
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/limaoper/bagi_pulsa/aplikasi/master/routes.py", line 300, in post_akun_bank
    kode_bank = hsl_data_bank[0]['kode_bank']
IndexError: list index out of range
2022-08-11 19:47:51,558 - aplikasi - ERROR - Exception on /master/post_akun_bank [POST]
Traceback (most recent call last):
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/limaoper/bagi_pulsa/aplikasi/master/routes.py", line 300, in post_akun_bank
    kode_bank = hsl_data_bank[0]['kode_bank']
IndexError: list index out of range
2022-08-11 19:47:51,701 - aplikasi - ERROR - Exception on /master/post_akun_bank [POST]
Traceback (most recent call last):
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/limaoper/bagi_pulsa/aplikasi/master/routes.py", line 300, in post_akun_bank
    kode_bank = hsl_data_bank[0]['kode_bank']
IndexError: list index out of range
2022-08-11 19:47:52,165 - aplikasi - ERROR - Exception on /master/post_akun_bank [POST]
Traceback (most recent call last):
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/limaoper/bagi_pulsa/aplikasi/master/routes.py", line 300, in post_akun_bank
    kode_bank = hsl_data_bank[0]['kode_bank']
IndexError: list index out of range
2022-08-11 19:47:52,206 - aplikasi - ERROR - Exception on /master/post_akun_bank [POST]
Traceback (most recent call last):
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/limaoper/bagi_pulsa/aplikasi/master/routes.py", line 300, in post_akun_bank
    kode_bank = hsl_data_bank[0]['kode_bank']
IndexError: list index out of range
2022-08-11 19:47:52,304 - aplikasi - ERROR - Exception on /master/post_akun_bank [POST]
Traceback (most recent call last):
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/limaoper/bagi_pulsa/aplikasi/master/routes.py", line 300, in post_akun_bank
    kode_bank = hsl_data_bank[0]['kode_bank']
IndexError: list index out of range
2022-08-11 19:47:52,651 - aplikasi - ERROR - Exception on /master/post_akun_bank [POST]
Traceback (most recent call last):
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/limaoper/bagi_pulsa/aplikasi/master/routes.py", line 300, in post_akun_bank
    kode_bank = hsl_data_bank[0]['kode_bank']
IndexError: list index out of range
2022-08-11 19:47:52,876 - aplikasi - ERROR - Exception on /master/post_akun_bank [POST]
Traceback (most recent call last):
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/limaoper/bagi_pulsa/aplikasi/master/routes.py", line 300, in post_akun_bank
    kode_bank = hsl_data_bank[0]['kode_bank']
IndexError: list index out of range
2022-08-11 19:47:53,094 - aplikasi - ERROR - Exception on /master/post_akun_bank [POST]
Traceback (most recent call last):
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/limaoper/bagi_pulsa/aplikasi/master/routes.py", line 300, in post_akun_bank
    kode_bank = hsl_data_bank[0]['kode_bank']
IndexError: list index out of range
2022-08-11 19:47:53,501 - aplikasi - ERROR - Exception on /master/post_akun_bank [POST]
Traceback (most recent call last):
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/limaoper/bagi_pulsa/aplikasi/master/routes.py", line 300, in post_akun_bank
    kode_bank = hsl_data_bank[0]['kode_bank']
IndexError: list index out of range
2022-08-12 07:40:27,076 - aplikasi - ERROR - Exception on /master/post_akun_bank [POST]
Traceback (most recent call last):
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/limaoper/bagi_pulsa/aplikasi/master/routes.py", line 300, in post_akun_bank
    kode_bank = hsl_data_bank[0]['kode_bank']
IndexError: list index out of range
2022-08-12 11:39:29,663 - root - ERROR - (1130, "ursa.jagoanhosting.com' is not allowed to connect to this MariaDB server")
Traceback (most recent call last):
  File "/home/limaoper/bagi_pulsa/aplikasi/utils.py", line 49, in db_fetch
    return pd.read_sql(sql, con=db_con(), params=param)
  File "/home/limaoper/bagi_pulsa/aplikasi/utils.py", line 39, in db_con
    g.bagi_pulsa = _connect_db()
  File "/home/limaoper/bagi_pulsa/aplikasi/utils.py", line 15, in _connect_db
    cursorclass=pymysql.cursors.DictCursor
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/pymysql/connections.py", line 353, in __init__
    self.connect()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/pymysql/connections.py", line 632, in connect
    self._get_server_information()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/pymysql/connections.py", line 1055, in _get_server_information
    packet = self._read_packet()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/limaoper/virtualenv/bagi_pulsa/3.7/lib/python3.7/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1130, "ursa.jagoanhosting.com' is not allowed to connect to this MariaDB server")
